const PROFILES_FETCH_REQUEST = 'profiles/FETCH_REQUEST';
const PROFILES_FETCH_SUCCESS = 'profiles/FETCH_SUCCESS';
const PROFILES_FETCH_ERROR = 'profiles/FETCH_ERROR';

export default {
  PROFILES_FETCH_REQUEST,
  PROFILES_FETCH_SUCCESS,
  PROFILES_FETCH_ERROR,
};
