const USER_FETCH_REQUEST = 'user/USER_FETCH_REQUEST';
const USER_FETCH_SUCCESS = 'user/USER_FETCH_SUCCESS';
const USER_FETCH_ERROR = 'user/USER_FETCH_ERROR';

export default {
  USER_FETCH_REQUEST,
  USER_FETCH_SUCCESS,
  USER_FETCH_ERROR,
};
